name: mqtt_server
description: A lightweight, efficient MQTT broker implementation in pure Dart that can be embedded in applications or run as a standalone server.
version: 2.0.0
homepage: https://github.com/salah-taha/dart_mqtt_server
repository: https://github.com/salah-taha/dart_mqtt_server
issue_tracker: https://github.com/salah-taha/dart_mqtt_server/issues

environment:
  sdk: ^3.0.0

dependencies:
  crypto: ^3.0.2
  shelf: ^1.4.1
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

topics:
  - mqtt
  - broker
  - iot
  - networking
  - server
